version: "3"
services:
  ecto_url_bug_database:
    image: postgres
    environment:
      - POSTGRES_USER=ecto_url_bug
      - POSTGRES_PASSWORD=ecto_url_bug
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecto_url_bug"]
      interval: 1s
      retries: 50
    networks:
      - foundation
    ports:
      - 35432:5432
    volumes:
      - ecto-url-bug-db-data:/var/lib/postgresql/data
networks:
  foundation:
volumes:
  ecto-url-bug-db-data:
